# Generated by Django 2.2 on 2020-12-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20181019_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
